name: Test
description: Run tests

inputs:
  node-version:
    required: true
    description: Node version to use for action

runs:
  using: composite
  steps:
    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Typecheck
      shell: bash
      run: npm run typecheck

    - name: Lint
      shell: bash
      run: npm run lint

    - name: Format check
      shell: bash
      run: npm run format:check
